### ISSUE TITLE
'tests' namespace conflict

### ISSUE THREAD

**Issue by edwinheij** [ta-tikoma/phpunit-architecture-test#12]
There should be a good reason to add a 'tests' namespace to the ```tests/TestCase.php``` file. Can you explain why and maybe why I'm struggling with my editor (notice case difference too).

![image](https://github.com/ta-tikoma/phpunit-architecture-test/assets/1799101/798cd143-ecd1-4d05-800d-4529206f5b5e)

**Comment by ta-tikoma** [comment]
Show me more about this file. 
Show your `TestCase`

**Comment by edwinheij** [comment]
Forget this one...

**Comment by ta-tikoma** [comment]
> Forget this one...

please show you `TestCase` file
